// Multi-language support for CampusBite platform

export const languages = {
  en: {
    name: 'English',
    flag: '🇺🇸'
  },
  te: {
    name: 'తెలుగు',
    flag: '🇮🇳'
  },
  hi: {
    name: 'हिन्दी',
    flag: '🇮🇳'
  }
};

export const translations = {
  en: {
    // Common
    appName: 'CampusBite',
    login: 'Login',
    logout: 'Logout',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    search: 'Search',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    
    // Login
    welcomeToCampusBite: 'Welcome to CampusBite',
    signInToAccount: 'Sign in to your account to continue',
    selectRole: 'Select your role',
    student: 'Student',
    admin: 'Admin',
    emailAddress: 'Email Address',
    password: 'Password',
    signIn: 'Sign In',
    onlyHitamEmails: 'Only @hitam.org email addresses are allowed',
    demoCredentials: 'Demo Credentials:',
    studentDemo: 'Student: student@hitam.org / password123',
    adminDemo: 'Admin: admin@hitam.org / password123',
    
    // Navigation
    menu: 'Menu',
    orders: 'Orders',
    dashboard: 'Dashboard',
    analytics: 'Analytics',
    
    // Menu
    ourMenu: 'Our Menu',
    deliciousMeals: 'Delicious meals prepared fresh daily',
    searchForDishes: 'Search for dishes...',
    addToCart: 'Add to Cart',
    itemsInCart: 'items in cart',
    viewCart: 'View Cart',
    noItemsFound: 'No items found',
    tryAdjustingSearch: 'Try adjusting your search or filter criteria',
    
    // Cart
    yourCart: 'Your Cart',
    reviewOrder: 'Review your order and proceed to checkout',
    requiredByTime: 'Required By Time',
    minimum30Minutes: 'Minimum 30 minutes from now',
    subtotal: 'Subtotal',
    serviceCharge: 'Service Charge',
    tax: 'Tax',
    total: 'Total',
    proceedToPayment: 'Proceed to Payment',
    paymentProcessedSecurely: 'Payment will be processed securely',
    yourCartIsEmpty: 'Your cart is empty',
    addDeliciousItems: 'Add some delicious items from our menu to get started',
    browseMenu: 'Browse Menu',
    
    // Orders
    orderHistory: 'Order History',
    trackOrders: 'Track your orders and view order details',
    startByPlacing: 'Start by placing your first order from our menu',
    orderNumber: 'Order #',
    requiredBy: 'Required by:',
    viewDetails: 'View Details',
    orderDetails: 'Order Details',
    orderDate: 'Order Date',
    status: 'Status',
    paymentStatus: 'Payment Status',
    orderItems: 'Order Items',
    quantity: 'Quantity',
    totalAmount: 'Total Amount',
    
    // Notifications
    notifications: 'Notifications',
    stayUpdated: 'Stay updated with your order status and important updates',
    noNotifications: 'No notifications',
    receiveNotifications: 'You\'ll receive notifications about your orders and important updates here',
    markAllAsRead: 'Mark All as Read',
    totalNotifications: 'Total Notifications',
    unread: 'Unread',
    read: 'Read',
    
    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    manageOrders: 'Manage orders and monitor canteen operations',
    totalOrders: 'Total Orders',
    pending: 'Pending',
    preparing: 'Preparing',
    ready: 'Ready',
    completed: 'Completed',
    cancelled: 'Cancelled',
    totalRevenue: 'Total Revenue',
    recentOrders: 'Recent Orders',
    refresh: 'Refresh',
    updateStatus: 'Update Status',
    studentRole: 'Student',
    items: 'items',
    amount: 'Amount',
    actions: 'Actions',
    noOrdersYet: 'No orders yet',
    ordersWillAppear: 'Orders will appear here as students place them',
    
    // Menu Management
    menuManagement: 'Menu Management',
    addEditManage: 'Add, edit, and manage menu items',
    addMenuItem: 'Add Menu Item',
    searchMenuItems: 'Search menu items...',
    editMenuItem: 'Edit Menu Item',
    itemName: 'Item Name',
    category: 'Category',
    description: 'Description',
    price: 'Price (₹)',
    preparationTime: 'Preparation Time (min)',
    imageUrl: 'Image URL',
    updateItem: 'Update Item',
    addItem: 'Add Item',
    noMenuItemsFound: 'No menu items found',
    startByAdding: 'Start by adding your first menu item',
    tryAdjustingCriteria: 'Try adjusting your search or filter criteria',
    
    // Analytics
    analyticsDashboard: 'Analytics Dashboard',
    insightsIntoPerformance: 'Insights into canteen performance and trends',
    generatePdfReport: 'Generate PDF Report',
    totalItems: 'Total Items',
    peakHour: 'Peak Hour',
    avgPrepTime: 'Avg Prep Time',
    weeklyRevenue: 'Weekly Revenue',
    mostPopularItems: 'Most Popular Items',
    peakOrderHours: 'Peak Order Hours',
    dailyRevenueTrend: 'Daily Revenue Trend',
    customerSatisfaction: 'Customer Satisfaction',
    averageRating: 'Average Rating',
    orderCompletionRate: 'Order Completion Rate',
    onTimeDelivery: 'On-Time Delivery',
    digitalReceiptsReports: 'Digital Receipts & Reports',
    generatePdfReports: 'Generate PDF Reports',
    createDetailedReports: 'Create detailed reports for daily, weekly, or monthly analytics',
    dailyReport: 'Daily Report',
    weeklyReport: 'Weekly Report',
    monthlyReport: 'Monthly Report'
  },
  
  te: {
    // Common
    appName: 'క్యాంపస్ బైట్',
    login: 'లాగిన్',
    logout: 'లాగ్ అవుట్',
    cancel: 'రద్దు చేయి',
    save: 'సేవ్',
    edit: 'ఎడిట్',
    delete: 'డిలీట్',
    add: 'జోడించు',
    search: 'వెతుకు',
    loading: 'లోడ్ అవుతోంది...',
    error: 'లోపం',
    success: 'విజయం',
    
    // Login
    welcomeToCampusBite: 'క్యాంపస్ బైట్‌కు స్వాగతం',
    signInToAccount: 'కొనసాగించడానికి మీ ఖాతాలోకి సైన్ ఇన్ చేయండి',
    selectRole: 'మీ పాత్రను ఎంచుకోండి',
    student: 'విద్యార్థి',
    admin: 'అడ్మిన్',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    signIn: 'సైన్ ఇన్',
    onlyHitamEmails: '@hitam.org ఇమెయిల్ చిరునామాలు మాత్రమే అనుమతించబడతాయి',
    demoCredentials: 'డెమో క్రెడెన్షియల్స్:',
    studentDemo: 'విద్యార్థి: student@hitam.org / password123',
    adminDemo: 'అడ్మిన్: admin@hitam.org / password123',
    
    // Navigation
    menu: 'మెనూ',
    orders: 'ఆర్డర్లు',
    dashboard: 'డాష్‌బోర్డ్',
    analytics: 'విశ్లేషణ',
    
    // Menu
    ourMenu: 'మా మెనూ',
    deliciousMeals: 'రోజు తాజాగా తయారుచేసిన రుచికరమైన ఆహారం',
    searchForDishes: 'వంటకాల కోసం వెతుకు...',
    addToCart: 'కార్ట్‌లో జోడించు',
    itemsInCart: 'వస్తువులు కార్ట్‌లో',
    viewCart: 'కార్ట్ చూడండి',
    noItemsFound: 'వస్తువులు కనుగొనబడలేదు',
    tryAdjustingSearch: 'మీ శోధన లేదా ఫిల్టర్ ప్రమాణాలను సర్దుబాటు చేయడానికి ప్రయత్నించండి',
    
    // Cart
    yourCart: 'మీ కార్ట్',
    reviewOrder: 'మీ ఆర్డర్‌ను సమీక్షించి చెక్‌అవుట్‌కు ముందుకు వెళ్లండి',
    requiredByTime: 'అవసరమైన సమయం',
    minimum30Minutes: 'ఇప్పటి నుండి కనీసం 30 నిమిషాలు',
    subtotal: 'ఉప మొత్తం',
    serviceCharge: 'సేవా ఛార్జ్',
    tax: 'పన్ను',
    total: 'మొత్తం',
    proceedToPayment: 'చెల్లింపుకు ముందుకు వెళ్లండి',
    paymentProcessedSecurely: 'చెల్లింపు సురక్షితంగా ప్రాసెస్ చేయబడుతుంది',
    yourCartIsEmpty: 'మీ కార్ట్ ఖాళీగా ఉంది',
    addDeliciousItems: 'మా మెనూ నుండి కొన్ని రుచికరమైన వస్తువులను జోడించండి',
    browseMenu: 'మెనూ బ్రౌజ్ చేయండి',
    
    // Orders
    orderHistory: 'ఆర్డర్ చరిత్ర',
    trackOrders: 'మీ ఆర్డర్లను ట్రాక్ చేయండి మరియు ఆర్డర్ వివరాలను చూడండి',
    startByPlacing: 'మా మెనూ నుండి మీ మొదటి ఆర్డర్‌ను ఇవ్వడం ద్వారా ప్రారంభించండి',
    orderNumber: 'ఆర్డర్ #',
    requiredBy: 'అవసరమైనది:',
    viewDetails: 'వివరాలను చూడండి',
    orderDetails: 'ఆర్డర్ వివరాలు',
    orderDate: 'ఆర్డర్ తేదీ',
    status: 'స్థితి',
    paymentStatus: 'చెల్లింపు స్థితి',
    orderItems: 'ఆర్డర్ వస్తువులు',
    quantity: 'పరిమాణం',
    totalAmount: 'మొత్తం మొత్తం',
    
    // Notifications
    notifications: 'నోటిఫికేషన్లు',
    stayUpdated: 'మీ ఆర్డర్ స్థితి మరియు ముఖ్యమైన నవీకరణలతో తాజాగా ఉండండి',
    noNotifications: 'నోటిఫికేషన్లు లేవు',
    receiveNotifications: 'మీ ఆర్డర్లు మరియు ముఖ్యమైన నవీకరణల గురించి మీరు ఇక్కడ నోటిఫికేషన్లు అందుకుంటారు',
    markAllAsRead: 'అన్నింటినీ చదివినట్లు గుర్తించండి',
    totalNotifications: 'మొత్తం నోటిఫికేషన్లు',
    unread: 'చదవనివి',
    read: 'చదివినవి',
    
    // Admin Dashboard
    adminDashboard: 'అడ్మిన్ డాష్‌బోర్డ్',
    manageOrders: 'ఆర్డర్లను నిర్వహించండి మరియు క్యాంటీన్ కార్యకలాపాలను పర్యవేక్షించండి',
    totalOrders: 'మొత్తం ఆర్డర్లు',
    pending: 'పెండింగ్',
    preparing: 'తయారుచేస్తోంది',
    ready: 'సిద్ధం',
    completed: 'పూర్తయింది',
    cancelled: 'రద్దు చేయబడింది',
    totalRevenue: 'మొత్తం ఆదాయం',
    recentOrders: 'ఇటీవలి ఆర్డర్లు',
    refresh: 'రిఫ్రెష్',
    updateStatus: 'స్థితిని నవీకరించండి',
    studentRole: 'విద్యార్థి',
    items: 'వస్తువులు',
    amount: 'మొత్తం',
    actions: 'చర్యలు',
    noOrdersYet: 'ఇంకా ఆర్డర్లు లేవు',
    ordersWillAppear: 'విద్యార్థులు వాటిని ఇచ్చినప్పుడు ఆర్డర్లు ఇక్కడ కనిపిస్తాయి',
    
    // Menu Management
    menuManagement: 'మెనూ నిర్వహణ',
    addEditManage: 'మెనూ వస్తువులను జోడించండి, సవరించండి మరియు నిర్వహించండి',
    addMenuItem: 'మెనూ వస్తువును జోడించండి',
    searchMenuItems: 'మెనూ వస్తువులను వెతుకు...',
    editMenuItem: 'మెనూ వస్తువును సవరించండి',
    itemName: 'వస్తువు పేరు',
    category: 'వర్గం',
    description: 'వివరణ',
    price: 'ధర (₹)',
    preparationTime: 'తయారీ సమయం (నిమిషాలు)',
    imageUrl: 'ఇమేజ్ URL',
    updateItem: 'వస్తువును నవీకరించండి',
    addItem: 'వస్తువును జోడించండి',
    noMenuItemsFound: 'మెనూ వస్తువులు కనుగొనబడలేదు',
    startByAdding: 'మీ మొదటి మెనూ వస్తువును జోడించడం ద్వారా ప్రారంభించండి',
    tryAdjustingCriteria: 'మీ శోధన లేదా ఫిల్టర్ ప్రమాణాలను సర్దుబాటు చేయడానికి ప్రయత్నించండి',
    
    // Analytics
    analyticsDashboard: 'విశ్లేషణ డాష్‌బోర్డ్',
    insightsIntoPerformance: 'క్యాంటీన్ పనితీరు మరియు ధోరణుల గురించి అంతర్దృష్టులు',
    generatePdfReport: 'PDF నివేదికను ఉత్పత్తి చేయండి',
    totalItems: 'మొత్తం వస్తువులు',
    peakHour: 'పీక్ అవర్',
    avgPrepTime: 'సగటు తయారీ సమయం',
    weeklyRevenue: 'వారపు ఆదాయం',
    mostPopularItems: 'ఎక్కువగా ప్రజాదరణ పొందిన వస్తువులు',
    peakOrderHours: 'పీక్ ఆర్డర్ అవర్స్',
    dailyRevenueTrend: 'రోజువారీ ఆదాయ ధోరణి',
    customerSatisfaction: 'కస్టమర్ సంతృప్తి',
    averageRating: 'సగటు రేటింగ్',
    orderCompletionRate: 'ఆర్డర్ పూర్తి రేట్',
    onTimeDelivery: 'సమయానికి డెలివరీ',
    digitalReceiptsReports: 'డిజిటల్ రసీదులు మరియు నివేదికలు',
    generatePdfReports: 'PDF నివేదికలను ఉత్పత్తి చేయండి',
    createDetailedReports: 'రోజువారీ, వారపు లేదా నెలవారీ విశ్లేషణ కోసం వివరణాత్మక నివేదికలను సృష్టించండి',
    dailyReport: 'రోజువారీ నివేదిక',
    weeklyReport: 'వారపు నివేదిక',
    monthlyReport: 'నెలవారీ నివేదిక'
  },
  
  hi: {
    // Common
    appName: 'कैंपस बाइट',
    login: 'लॉगिन',
    logout: 'लॉग आउट',
    cancel: 'रद्द करें',
    save: 'सेव करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    add: 'जोड़ें',
    search: 'खोजें',
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
    
    // Login
    welcomeToCampusBite: 'कैंपस बाइट में आपका स्वागत है',
    signInToAccount: 'जारी रखने के लिए अपने खाते में साइन इन करें',
    selectRole: 'अपनी भूमिका चुनें',
    student: 'छात्र',
    admin: 'एडमिन',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    signIn: 'साइन इन',
    onlyHitamEmails: 'केवल @hitam.org ईमेल पते की अनुमति है',
    demoCredentials: 'डेमो क्रेडेंशियल्स:',
    studentDemo: 'छात्र: student@hitam.org / password123',
    adminDemo: 'एडमिन: admin@hitam.org / password123',
    
    // Navigation
    menu: 'मेनू',
    orders: 'ऑर्डर',
    dashboard: 'डैशबोर्ड',
    analytics: 'विश्लेषण',
    
    // Menu
    ourMenu: 'हमारा मेनू',
    deliciousMeals: 'ताजा तैयार स्वादिष्ट भोजन',
    searchForDishes: 'व्यंजन खोजें...',
    addToCart: 'कार्ट में जोड़ें',
    itemsInCart: 'आइटम कार्ट में',
    viewCart: 'कार्ट देखें',
    noItemsFound: 'कोई आइटम नहीं मिला',
    tryAdjustingSearch: 'अपने खोज या फिल्टर मानदंड को समायोजित करने का प्रयास करें',
    
    // Cart
    yourCart: 'आपका कार्ट',
    reviewOrder: 'अपने ऑर्डर की समीक्षा करें और चेकआउट के लिए आगे बढ़ें',
    requiredByTime: 'आवश्यक समय',
    minimum30Minutes: 'अब से कम से कम 30 मिनट',
    subtotal: 'उप-योग',
    serviceCharge: 'सेवा शुल्क',
    tax: 'कर',
    total: 'कुल',
    proceedToPayment: 'भुगतान के लिए आगे बढ़ें',
    paymentProcessedSecurely: 'भुगतान सुरक्षित रूप से प्रसंस्कृत किया जाएगा',
    yourCartIsEmpty: 'आपका कार्ट खाली है',
    addDeliciousItems: 'हमारे मेनू से कुछ स्वादिष्ट आइटम जोड़ें',
    browseMenu: 'मेनू ब्राउज़ करें',
    
    // Orders
    orderHistory: 'ऑर्डर इतिहास',
    trackOrders: 'अपने ऑर्डर को ट्रैक करें और ऑर्डर विवरण देखें',
    startByPlacing: 'हमारे मेनू से अपना पहला ऑर्डर देकर शुरू करें',
    orderNumber: 'ऑर्डर #',
    requiredBy: 'आवश्यक:',
    viewDetails: 'विवरण देखें',
    orderDetails: 'ऑर्डर विवरण',
    orderDate: 'ऑर्डर तिथि',
    status: 'स्थिति',
    paymentStatus: 'भुगतान स्थिति',
    orderItems: 'ऑर्डर आइटम',
    quantity: 'मात्रा',
    totalAmount: 'कुल राशि',
    
    // Notifications
    notifications: 'सूचनाएं',
    stayUpdated: 'अपने ऑर्डर स्थिति और महत्वपूर्ण अपडेट के साथ अपडेट रहें',
    noNotifications: 'कोई सूचना नहीं',
    receiveNotifications: 'आपको अपने ऑर्डर और महत्वपूर्ण अपडेट के बारे में यहां सूचनाएं मिलेंगी',
    markAllAsRead: 'सभी को पढ़ा हुआ चिह्नित करें',
    totalNotifications: 'कुल सूचनाएं',
    unread: 'अपठित',
    read: 'पढ़ा हुआ',
    
    // Admin Dashboard
    adminDashboard: 'एडमिन डैशबोर्ड',
    manageOrders: 'ऑर्डर प्रबंधित करें और कैंटीन संचालन की निगरानी करें',
    totalOrders: 'कुल ऑर्डर',
    pending: 'लंबित',
    preparing: 'तैयार हो रहा',
    ready: 'तैयार',
    completed: 'पूर्ण',
    cancelled: 'रद्द',
    totalRevenue: 'कुल राजस्व',
    recentOrders: 'हाल के ऑर्डर',
    refresh: 'रिफ्रेश',
    updateStatus: 'स्थिति अपडेट करें',
    studentRole: 'छात्र',
    items: 'आइटम',
    amount: 'राशि',
    actions: 'कार्य',
    noOrdersYet: 'अभी तक कोई ऑर्डर नहीं',
    ordersWillAppear: 'छात्रों द्वारा दिए जाने पर ऑर्डर यहां दिखाई देंगे',
    
    // Menu Management
    menuManagement: 'मेनू प्रबंधन',
    addEditManage: 'मेनू आइटम जोड़ें, संपादित करें और प्रबंधित करें',
    addMenuItem: 'मेनू आइटम जोड़ें',
    searchMenuItems: 'मेनू आइटम खोजें...',
    editMenuItem: 'मेनू आइटम संपादित करें',
    itemName: 'आइटम नाम',
    category: 'श्रेणी',
    description: 'विवरण',
    price: 'मूल्य (₹)',
    preparationTime: 'तैयारी का समय (मिनट)',
    imageUrl: 'छवि URL',
    updateItem: 'आइटम अपडेट करें',
    addItem: 'आइटम जोड़ें',
    noMenuItemsFound: 'कोई मेनू आइटम नहीं मिला',
    startByAdding: 'अपना पहला मेनू आइटम जोड़कर शुरू करें',
    tryAdjustingCriteria: 'अपने खोज या फिल्टर मानदंड को समायोजित करने का प्रयास करें',
    
    // Analytics
    analyticsDashboard: 'विश्लेषण डैशबोर्ड',
    insightsIntoPerformance: 'कैंटीन प्रदर्शन और रुझानों में अंतर्दृष्टि',
    generatePdfReport: 'PDF रिपोर्ट जेनरेट करें',
    totalItems: 'कुल आइटम',
    peakHour: 'पीक आवर',
    avgPrepTime: 'औसत तैयारी समय',
    weeklyRevenue: 'साप्ताहिक राजस्व',
    mostPopularItems: 'सबसे लोकप्रिय आइटम',
    peakOrderHours: 'पीक ऑर्डर आवर्स',
    dailyRevenueTrend: 'दैनिक राजस्व रुझान',
    customerSatisfaction: 'ग्राहक संतुष्टि',
    averageRating: 'औसत रेटिंग',
    orderCompletionRate: 'ऑर्डर पूर्णता दर',
    onTimeDelivery: 'समय पर डिलीवरी',
    digitalReceiptsReports: 'डिजिटल रसीदें और रिपोर्ट्स',
    generatePdfReports: 'PDF रिपोर्ट्स जेनरेट करें',
    createDetailedReports: 'दैनिक, साप्ताहिक या मासिक विश्लेषण के लिए विस्तृत रिपोर्ट्स बनाएं',
    dailyReport: 'दैनिक रिपोर्ट',
    weeklyReport: 'साप्ताहिक रिपोर्ट',
    monthlyReport: 'मासिक रिपोर्ट'
  }
};

export const getTranslation = (key, language = 'en') => {
  return translations[language]?.[key] || translations['en'][key] || key;
};
